# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
  "VERSION",
  "**.md",
  "api/**",
  "apiv2/**",
  "bulk-import-tools/**",
  "exporters-inventory/**",
  "inventory/**",
  "tenant-controller/**",
]

precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
